export const subscriberTabs = [
  'All Subscribers',
  'Active',
  'Expiring Soon',
  'Expired',
  'Cancelled',
];

export const subscriberStats = [
  {
    label: 'Active Subscribers',
    value: '1,245',
    change: '12%',
    changeType: 'positive',
    icon: 'Users',
    color: '#10b981',
  },
  {
    label: 'MRR',
    value: '$4,872.50',
    change: '15%',
    changeType: 'positive',
    icon: 'DollarSign',
    color: '#3b82f6',
  },
  {
    label: 'New Subscribers',
    value: '187',
    change: '18%',
    changeType: 'positive',
    icon: 'UserPlus',
    color: '#9b51e0',
  },
  {
    label: 'Cancelled',
    value: '23',
    change: '8%',
    changeType: 'negative',
    icon: 'UserMinus',
    color: '#ef4444',
  },
];

export const subscribers = [
  {
    id: 1,
    name: 'Sarah Johnson',
    username: '@sarahjohnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    plan: 'Premium💎',
    planPrice: '$14.99 / month',
    planColor: '#3b82f6',
    renewalDate: 'May 30, 2024',
    daysUntilRenewal: 'in 5 days',
    status: 'Active',
    totalSpent: '$149.90',
  },
  {
    id: 2,
    name: 'Michael Thompson',
    username: '@mike_t92',
    avatar: 'https://i.pravatar.cc/150?img=3',
    plan: 'VIP🔥',
    planPrice: '$29.99 / month',
    planColor: '#f59e0b',
    renewalDate: 'Jun 2, 2024',
    daysUntilRenewal: 'in 8 days',
    status: 'Active',
    totalSpent: '$269.91',
  },
  {
    id: 3,
    name: 'Emma Davis',
    username: '@emmadavisxo',
    avatar: 'https://i.pravatar.cc/150?img=5',
    plan: 'Premium💎',
    planPrice: '$14.99 / month',
    planColor: '#3b82f6',
    renewalDate: 'May 25, 2024',
    daysUntilRenewal: 'Today',
    status: 'Expiring Soon',
    totalSpent: '$104.93',
  },
  {
    id: 4,
    name: 'David Wilson',
    username: '@dave_wilson',
    avatar: 'https://i.pravatar.cc/150?img=7',
    plan: 'VIP🔥',
    planPrice: '$29.99 / month',
    planColor: '#f59e0b',
    renewalDate: 'May 24, 2024',
    daysUntilRenewal: 'Yesterday',
    status: 'Expired',
    totalSpent: '$119.96',
  },
  {
    id: 5,
    name: 'Olivia Martinez',
    username: '@oliviamartinez',
    avatar: 'https://i.pravatar.cc/150?img=9',
    plan: 'Premium💎',
    planPrice: '$14.99 / month',
    planColor: '#3b82f6',
    renewalDate: 'Jun 8, 2024',
    daysUntilRenewal: 'in 14 days',
    status: 'Active',
    totalSpent: '$164.89',
  },
  {
    id: 6,
    name: 'James Anderson',
    username: '@j_anderson',
    avatar: 'https://i.pravatar.cc/150?img=11',
    plan: 'VIP🔥',
    planPrice: '$29.99 / month',
    planColor: '#f59e0b',
    renewalDate: 'Jun 12, 2024',
    daysUntilRenewal: 'in 18 days',
    status: 'Active',
    totalSpent: '$299.90',
  },
  {
    id: 7,
    name: 'Sophia Brown',
    username: '@sophiabrown',
    avatar: 'https://i.pravatar.cc/150?img=13',
    plan: 'Premium💎',
    planPrice: '$14.99 / month',
    planColor: '#3b82f6',
    renewalDate: 'May 10, 2024',
    daysUntilRenewal: '15 days ago',
    status: 'Cancelled',
    totalSpent: '$59.96',
  },
  {
    id: 8,
    name: 'Daniel Garcia',
    username: '@danielgarcia',
    avatar: 'https://i.pravatar.cc/150?img=15',
    plan: 'VIP🔥',
    planPrice: '$29.99 / month',
    planColor: '#f59e0b',
    renewalDate: 'May 3, 2024',
    daysUntilRenewal: '22 days ago',
    status: 'Cancelled',
    totalSpent: '$89.97',
  },
  {
    id: 9,
    name: 'Emily Chen',
    username: '@emilychen',
    avatar: 'https://i.pravatar.cc/150?img=17',
    plan: 'Premium💎',
    planPrice: '$14.99 / month',
    planColor: '#3b82f6',
    renewalDate: 'Jun 15, 2024',
    daysUntilRenewal: 'in 21 days',
    status: 'Active',
    totalSpent: '$134.91',
  },
  {
    id: 10,
    name: 'Ryan Taylor',
    username: '@ryantaylor',
    avatar: 'https://i.pravatar.cc/150?img=19',
    plan: 'VIP🔥',
    planPrice: '$29.99 / month',
    planColor: '#f59e0b',
    renewalDate: 'Jun 20, 2024',
    daysUntilRenewal: 'in 26 days',
    status: 'Active',
    totalSpent: '$329.89',
  },
];

export const subscribersOverview = {
  total: '1,245',
  change: '12%',
  changeType: 'positive',
  chartData: [
    { label: 'Apr 28', value: 980 },
    { label: 'May 5', value: 1050 },
    { label: 'May 12', value: 1120 },
    { label: 'May 19', value: 1180 },
    { label: 'May 26', value: 1245 },
  ],
};

export const planBreakdown = {
  total: 1245,
  categories: [
    { label: 'Premium', percentage: 58, count: 720, color: '#3b82f6' },
    { label: 'VIP', percentage: 33, count: 405, color: '#f59e0b' },
    { label: 'Basic', percentage: 9, count: 120, color: '#10b981' },
  ],
};

export const topSubscribers = [
  { id: 1, name: 'James Anderson', username: '@j_anderson', avatar: 'https://i.pravatar.cc/150?img=11', spent: '$299.90' },
  { id: 2, name: 'Michael Thompson', username: '@mike_t92', avatar: 'https://i.pravatar.cc/150?img=3', spent: '$269.91' },
  { id: 3, name: 'Olivia Martinez', username: '@oliviamartinez', avatar: 'https://i.pravatar.cc/150?img=9', spent: '$164.89' },
  { id: 4, name: 'Sarah Johnson', username: '@sarahjohnson', avatar: 'https://i.pravatar.cc/150?img=1', spent: '$149.90' },
  { id: 5, name: 'David Wilson', username: '@dave_wilson', avatar: 'https://i.pravatar.cc/150?img=7', spent: '$119.96' },
];

export const engagementInsights = [
  { label: 'Avg. Messages Sent', value: '24.6', change: '18%', changeType: 'positive' },
  { label: 'Avg. Tips Received', value: '$56.30', change: '16%', changeType: 'positive' },
  { label: 'PPV Purchases', value: '356', change: '12%', changeType: 'positive' },
];

export const pagination = {
  totalPages: 156,
  currentPage: 1,
};
